# Start with a minimal pipeline that you can customize to build and deploy your code.
trigger:
- main

pool:
  name: Default

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'app/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
#     sonarQubeRunAnalysis: false
- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Service Connection'
    AnalysisService: 'Veracode'
    veracodeAppProfile: 'RRRTEST'
    version: '$(build.buildNumber)'
    filepath: 'app/target/verademo.war'
    optargs: '-deleteIncompleteScan 2'
    failBuildIfUploadAndScanBuildStepFails: true
    importResults: true
    maximumWaitTime: '120'

# - task: Veracode Flaw Importer@3
#   inputs:
#     ConnectionDetailsSelection: 'Service Connection'
#     AnalysisService: 'Veracode'
#     veracodeAppProfile: 'TESTjava'
#     sandboxName: 
#     scanType: 'Static Analysis'
#     importType: 'All Flaws'
#     workItemType: 'Bug'
#     area: '$(system.teamProject)'
#     overwriteAreaPathInWorkItemsOnImport: true
#     iterationPath: '$(system.teamProject)'
#     overwriteIterationPath: true
#     flawImportLimit: '25'
